(define (problem lec-16-R4-S4-P40)
    (:domain lec-winter-split)
    (:objects
        team-1 team-2 team-3 team-4 team-5 team-6 team-7 team-8 team-9 team-10 team-11 team-12 team-13 team-14 team-15 team-16 - team
        m1 m2 m3 m4 m5 m6 m7 m8 m9 m10 m11 m12 m13 m14 m15 - match
        ref-1 ref-2 ref-3 ref-4 - referee
        server-1 server-2 server-3 server-4 - server
    )
    (:init
        (ref-available ref-1)
        (ref-available ref-2)
        (ref-available ref-3)
        (ref-available ref-4)
        (server-available server-1)
        (server-available server-2)
        (server-available server-3)
        (server-available server-4)
        (participant team-1 m1 home)
        (participant team-2 m1 away)
        (participant team-3 m2 home)
        (participant team-4 m2 away)
        (participant team-5 m3 home)
        (participant team-6 m3 away)
        (participant team-7 m4 home)
        (participant team-8 m4 away)
        (participant team-9 m5 home)
        (participant team-10 m5 away)
        (participant team-11 m6 home)
        (participant team-12 m6 away)
        (participant team-13 m7 home)
        (participant team-14 m7 away)
        (participant team-15 m8 home)
        (participant team-16 m8 away)
        (connected m1 m9 home)
        (connected m2 m9 away)
        (connected m3 m10 home)
        (connected m4 m10 away)
        (connected m5 m11 home)
        (connected m6 m11 away)
        (connected m7 m12 home)
        (connected m8 m12 away)
        (connected m9 m13 home)
        (connected m10 m13 away)
        (connected m11 m14 home)
        (connected m12 m14 away)
        (connected m13 m15 home)
        (connected m14 m15 away)
        (has-conflict m1)
        (has-conflict m2)
        (has-conflict m4)
        (has-conflict m6)
        (has-conflict m7)
        (has-conflict m11)
    )
    (:goal
        (verified m15)
    )
)