(define (problem lec-32-R32-S128-P40)
    (:domain lec-winter-split)
    (:objects
        team-1 team-2 team-3 team-4 team-5 team-6 team-7 team-8 team-9 team-10 team-11 team-12 team-13 team-14 team-15 team-16 team-17 team-18 team-19 team-20 team-21 team-22 team-23 team-24 team-25 team-26 team-27 team-28 team-29 team-30 team-31 team-32 - team
        m1 m2 m3 m4 m5 m6 m7 m8 m9 m10 m11 m12 m13 m14 m15 m16 m17 m18 m19 m20 m21 m22 m23 m24 m25 m26 m27 m28 m29 m30 m31 - match
        ref-1 ref-2 ref-3 ref-4 ref-5 ref-6 ref-7 ref-8 ref-9 ref-10 ref-11 ref-12 ref-13 ref-14 ref-15 ref-16 ref-17 ref-18 ref-19 ref-20 ref-21 ref-22 ref-23 ref-24 ref-25 ref-26 ref-27 ref-28 ref-29 ref-30 ref-31 ref-32 - referee
        server-1 server-2 server-3 server-4 server-5 server-6 server-7 server-8 server-9 server-10 server-11 server-12 server-13 server-14 server-15 server-16 server-17 server-18 server-19 server-20 server-21 server-22 server-23 server-24 server-25 server-26 server-27 server-28 server-29 server-30 server-31 server-32 server-33 server-34 server-35 server-36 server-37 server-38 server-39 server-40 server-41 server-42 server-43 server-44 server-45 server-46 server-47 server-48 server-49 server-50 server-51 server-52 server-53 server-54 server-55 server-56 server-57 server-58 server-59 server-60 server-61 server-62 server-63 server-64 server-65 server-66 server-67 server-68 server-69 server-70 server-71 server-72 server-73 server-74 server-75 server-76 server-77 server-78 server-79 server-80 server-81 server-82 server-83 server-84 server-85 server-86 server-87 server-88 server-89 server-90 server-91 server-92 server-93 server-94 server-95 server-96 server-97 server-98 server-99 server-100 server-101 server-102 server-103 server-104 server-105 server-106 server-107 server-108 server-109 server-110 server-111 server-112 server-113 server-114 server-115 server-116 server-117 server-118 server-119 server-120 server-121 server-122 server-123 server-124 server-125 server-126 server-127 server-128 - server
    )
    (:init
        (ref-available ref-1)
        (ref-available ref-2)
        (ref-available ref-3)
        (ref-available ref-4)
        (ref-available ref-5)
        (ref-available ref-6)
        (ref-available ref-7)
        (ref-available ref-8)
        (ref-available ref-9)
        (ref-available ref-10)
        (ref-available ref-11)
        (ref-available ref-12)
        (ref-available ref-13)
        (ref-available ref-14)
        (ref-available ref-15)
        (ref-available ref-16)
        (ref-available ref-17)
        (ref-available ref-18)
        (ref-available ref-19)
        (ref-available ref-20)
        (ref-available ref-21)
        (ref-available ref-22)
        (ref-available ref-23)
        (ref-available ref-24)
        (ref-available ref-25)
        (ref-available ref-26)
        (ref-available ref-27)
        (ref-available ref-28)
        (ref-available ref-29)
        (ref-available ref-30)
        (ref-available ref-31)
        (ref-available ref-32)
        (server-available server-1)
        (server-available server-2)
        (server-available server-3)
        (server-available server-4)
        (server-available server-5)
        (server-available server-6)
        (server-available server-7)
        (server-available server-8)
        (server-available server-9)
        (server-available server-10)
        (server-available server-11)
        (server-available server-12)
        (server-available server-13)
        (server-available server-14)
        (server-available server-15)
        (server-available server-16)
        (server-available server-17)
        (server-available server-18)
        (server-available server-19)
        (server-available server-20)
        (server-available server-21)
        (server-available server-22)
        (server-available server-23)
        (server-available server-24)
        (server-available server-25)
        (server-available server-26)
        (server-available server-27)
        (server-available server-28)
        (server-available server-29)
        (server-available server-30)
        (server-available server-31)
        (server-available server-32)
        (server-available server-33)
        (server-available server-34)
        (server-available server-35)
        (server-available server-36)
        (server-available server-37)
        (server-available server-38)
        (server-available server-39)
        (server-available server-40)
        (server-available server-41)
        (server-available server-42)
        (server-available server-43)
        (server-available server-44)
        (server-available server-45)
        (server-available server-46)
        (server-available server-47)
        (server-available server-48)
        (server-available server-49)
        (server-available server-50)
        (server-available server-51)
        (server-available server-52)
        (server-available server-53)
        (server-available server-54)
        (server-available server-55)
        (server-available server-56)
        (server-available server-57)
        (server-available server-58)
        (server-available server-59)
        (server-available server-60)
        (server-available server-61)
        (server-available server-62)
        (server-available server-63)
        (server-available server-64)
        (server-available server-65)
        (server-available server-66)
        (server-available server-67)
        (server-available server-68)
        (server-available server-69)
        (server-available server-70)
        (server-available server-71)
        (server-available server-72)
        (server-available server-73)
        (server-available server-74)
        (server-available server-75)
        (server-available server-76)
        (server-available server-77)
        (server-available server-78)
        (server-available server-79)
        (server-available server-80)
        (server-available server-81)
        (server-available server-82)
        (server-available server-83)
        (server-available server-84)
        (server-available server-85)
        (server-available server-86)
        (server-available server-87)
        (server-available server-88)
        (server-available server-89)
        (server-available server-90)
        (server-available server-91)
        (server-available server-92)
        (server-available server-93)
        (server-available server-94)
        (server-available server-95)
        (server-available server-96)
        (server-available server-97)
        (server-available server-98)
        (server-available server-99)
        (server-available server-100)
        (server-available server-101)
        (server-available server-102)
        (server-available server-103)
        (server-available server-104)
        (server-available server-105)
        (server-available server-106)
        (server-available server-107)
        (server-available server-108)
        (server-available server-109)
        (server-available server-110)
        (server-available server-111)
        (server-available server-112)
        (server-available server-113)
        (server-available server-114)
        (server-available server-115)
        (server-available server-116)
        (server-available server-117)
        (server-available server-118)
        (server-available server-119)
        (server-available server-120)
        (server-available server-121)
        (server-available server-122)
        (server-available server-123)
        (server-available server-124)
        (server-available server-125)
        (server-available server-126)
        (server-available server-127)
        (server-available server-128)
        (participant team-1 m1 home)
        (participant team-2 m1 away)
        (participant team-3 m2 home)
        (participant team-4 m2 away)
        (participant team-5 m3 home)
        (participant team-6 m3 away)
        (participant team-7 m4 home)
        (participant team-8 m4 away)
        (participant team-9 m5 home)
        (participant team-10 m5 away)
        (participant team-11 m6 home)
        (participant team-12 m6 away)
        (participant team-13 m7 home)
        (participant team-14 m7 away)
        (participant team-15 m8 home)
        (participant team-16 m8 away)
        (participant team-17 m9 home)
        (participant team-18 m9 away)
        (participant team-19 m10 home)
        (participant team-20 m10 away)
        (participant team-21 m11 home)
        (participant team-22 m11 away)
        (participant team-23 m12 home)
        (participant team-24 m12 away)
        (participant team-25 m13 home)
        (participant team-26 m13 away)
        (participant team-27 m14 home)
        (participant team-28 m14 away)
        (participant team-29 m15 home)
        (participant team-30 m15 away)
        (participant team-31 m16 home)
        (participant team-32 m16 away)
        (connected m1 m17 home)
        (connected m2 m17 away)
        (connected m3 m18 home)
        (connected m4 m18 away)
        (connected m5 m19 home)
        (connected m6 m19 away)
        (connected m7 m20 home)
        (connected m8 m20 away)
        (connected m9 m21 home)
        (connected m10 m21 away)
        (connected m11 m22 home)
        (connected m12 m22 away)
        (connected m13 m23 home)
        (connected m14 m23 away)
        (connected m15 m24 home)
        (connected m16 m24 away)
        (connected m17 m25 home)
        (connected m18 m25 away)
        (connected m19 m26 home)
        (connected m20 m26 away)
        (connected m21 m27 home)
        (connected m22 m27 away)
        (connected m23 m28 home)
        (connected m24 m28 away)
        (connected m25 m29 home)
        (connected m26 m29 away)
        (connected m27 m30 home)
        (connected m28 m30 away)
        (connected m29 m31 home)
        (connected m30 m31 away)
        (has-conflict m6)
        (has-conflict m7)
        (has-conflict m10)
        (has-conflict m16)
        (has-conflict m17)
        (has-conflict m18)
        (has-conflict m21)
        (has-conflict m22)
        (has-conflict m24)
        (has-conflict m26)
        (has-conflict m27)
        (has-conflict m28)
        (has-conflict m31)
    )
    (:goal
        (verified m31)
    )
)